### ISSUE TITLE
Dependency List

### ISSUE THREAD

**Issue by Vhati** [OceanographyforEveryone/OpenCTD#1]
I've only ever dabbled in C, so I'm not sure how folks manage dependency hell.

I think I can safely recommend editing the readme to list your reqs.  : )
.
.
Some cursory googling turned up these links...
.
I2C library for the MS5803_14BA 14bar pressure sensor
https://github.com/millerlp/MS5803_14

Dallas Temperature Control for the DS18B20 thermometer
https://milesburton.com/Dallas_Temperature_Control_Library

OneWire **
http://www.pjrc.com/teensy/td_libs_OneWire.html
http://playground.arduino.cc/Learning/OneWire

SD *
https://www.arduino.cc/en/Reference/SD

SoftwareSerial *
http://www.pjrc.com/teensy/td_libs_SoftwareSerial.html
https://www.arduino.cc/en/Reference/SoftwareSerial

SPI **
https://www.pjrc.com/teensy/td_libs_SPI.html
https://www.arduino.cc/en/Reference/SPI

Wire *
http://www.pjrc.com/teensy/td_libs_Wire.html
https://www.arduino.cc/en/Reference/Wire

\* Included with Arduino.
*\* Included with Arduino. A newer version may be available.

(I backslashed the footnote asterisks, so they wouldn't turn into bullet lists)

**Comment by DrAndrewThaler** [comment]
Thank you!
