### ISSUE TITLE
Sample Breaks

### ISSUE THREAD

**Issue by DrAndrewThaler** [OceanographyforEveryone/OpenCTD#10]
Right now, the OpenCTD begins logging as soon as powered on without recording any break in the data. We need to add a feature that adds a sample number to the beginning of each sample series. For example, the first cast of the day starts with a "SAMPLE 1" line in datalog.txt. If the user then power cycles the device, the next time it starts recording is writes a "SAMPLE 2" line in datalog.txt where the new data begins. 

Does this make sense? Are there more elegant solutions?

**Comment by IanTBlack** [comment]
There is an logger demo by Adafruit that will create a newly labeled file every time the device is power cycled.

https://github.com/adafruit/Light-and-Temp-logger/blob/master/lighttemplogger.ino

I'll create a new pull request with my code that implements this.
