### ISSUE TITLE
How is the recommended SOIC to DIP adapter used in this project?

### ISSUE THREAD

**Issue by Jake-DeCicco** [OceanographyforEveryone/OpenCTD#19]
For a novice electronics enthusiast like myself, these building instructions are helpful, but I cannot figure out how this adapter should be used or if it even needs to be used at all. As with many concepts I've learned recently, I tried to find information on the internet but I came up short on the entire concept of switching between SOIC and DIP.

**Comment by IanTBlack** [comment]
Hi Jake,

I believe it is used if you decide to piece together the pressure sensor
yourself.

If you opted to use a premade one from SparkFun or Blue Robotics then you
won't need it.

Let me know if you have any other questions or need additional help.

Cheers,
- Ian
