### ISSUE TITLE
SoftwareSerial

### ISSUE THREAD

**Issue by Squidman32** [OceanographyforEveryone/OpenCTD#22]
HI Guys, I'm having a library problem, and I'm sure the answer is obvious, but I"m still in the early stages of the github/arduino learning curve.  I can't find the downloadable ZIP file of the modified SoftwareSerial library for the Adafruit feather CTD.  I can navigate to the code on the GitHub page and see it.  But only option I have is to try and cut and paste it, there is no zip/download.  Where can I find the downloadable zip to add the library  to Arduino IDE?

**Comment by IanTBlack** [comment]
Are you using the Feather 32u4 or Feather M0? If using the M0, you don't
need SoftwareSerial.
If you want me to give me your components specs, I might be able to fire up
some old code and give you a solution.

Cheers,
-------------
Ian Black
Faculty Research Assistant | Ocean Observing Center
College of Earth, Ocean, and Atmospheric Sciences | Oregon State University
Cell: (541) 817-3687

**Comment by DrAndrewThaler** [comment]
Hello! GitHub is terrible about making simple downloads easy. To get everything in a nice package you either need to clone the OpenCTD repository and then access the local version on your desktop, or download the entire OpenCTD repository: https://github.com/OceanographyforEveryone/OpenCTD and then navigate to the libraries in the unpacked .zip file.

**Comment by Squidman32** [comment]
Thanks for the super fast response!

I"m using the Feather MO.  when I compile/verify the sketch from GitHub I
get the following error

"Arduino: 1.6.13 (Mac OS X), Board: "Adafruit Feather M0, Arduino, Off"
Build options changed, rebuilding all
/Volumes/GoogleDrive/My Drive/3D Printer files/CTD parts/Feather logger
CTD/Adafruit_RTC_master_code/Adafruit_RTC_master_code.ino:17:28: fatal
error: SoftwareSerial.h: No such file or directory
 #include <SoftwareSerial.h>
 ^compilation terminated.
exit status 1
Error compiling for board Adafruit Feather M0.
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


I'm assuming because it terminates right after SoftwareSerial.h is
included, that's where the error is coming from.  Is that a bad assumption?

Lloyd
Lloyd Trueblood Ph.D.
Associate Professor and Chair
Biology Department

<https://lasierra.edu/>

Lloyd.Trueblood@lasierra.edu
Phone: (951) 785-2 <(951)+785-2105>521
Fax: (951) 785-2100

lasierra.edu  <https://brand.lasierra.edu/email-signatures/#>
4500 Riverwalk Parkway | Riverside, CA 92505

Confidentiality: This e-mail (including any attachments) may contain
confidential, proprietary and privileged information, and unauthorized
disclosure or use is prohibited. If you receive this email in error, please
notify the sender and delete this e-mail from your system.

**Comment by Squidman32** [comment]
Thanks Andrew, That got it for me.  After I got the whole library I was
able to place the SoftwareSerial in and it compiled.
Lloyd Trueblood Ph.D.
Associate Professor and Chair
Biology Department

<https://lasierra.edu/>

Lloyd.Trueblood@lasierra.edu
Phone: (951) 785-2 <(951)+785-2105>521
Fax: (951) 785-2100

lasierra.edu  <https://brand.lasierra.edu/email-signatures/#>
4500 Riverwalk Parkway | Riverside, CA 92505

Confidentiality: This e-mail (including any attachments) may contain
confidential, proprietary and privileged information, and unauthorized
disclosure or use is prohibited. If you receive this email in error, please
notify the sender and delete this e-mail from your system.
