### ISSUE TITLE
Robust comparison to commercial CTD?

### ISSUE THREAD

**Issue by camrinbraun** [OceanographyforEveryone/OpenCTD#24]
I see the 2 datasets included for comparison but surely there's data out there seeing how these stack up against any of the major CTDs in the coastal ocean? Trying to decide whether to embark on this project which depends on the accuracy and precision in conductivity primarily.

I also saw a comment in another issue on measuring DO. Any progress on that front?

Really cool tool you guys have created. Thanks!

**Comment by IanTBlack** [comment]
Hello,

I think I have some data on a hard drive somewhere with comparisons between
shipboard Sea-Bird CTD rosettes and YSI Castaways. I'll see if I can find
it. There were a few times that I deployed the CTDs to 100m, and after a
couple profiles they flooded (that's a manufacturing oversight on my part),
so repeated data on a single CTD is sparse.

In my build, I used the TSYS01 as the temperature sensor, which has been
great in building confidence in the temperature compensation of
conductivity.
Off the top of my head, there were days when I was able to achieve a 0.2
PSU difference from a vetted CTD, some days I was off by more than 1 PSU.
One source of error is probably in the environment that I calibrated the
Atlas K1.0 probe. I would often calibrate the conductivity probe in my
kitchen, not really considering ambient temperature or attempting repeated
calibrations. I once calibrated one of my open source CTDs in a cold room
and noticed an improvement. I think that was the one that had to 0.2 PSU
difference. If you have access to a temperature controlled lab or
refrigerator, I would recommend performing calibrations that way.

I think noise in the circuit also causes some issues in the accuracy and
precision in the conductivity reading. Atlas-Scientific offers voltage
isolators for their EC EZOs. At the very least, it should make a reading
stable, so then you could hone the accuracy through calibration. You may be
able to find other conductivity probes that work, but when I last looked a
couple of years ago, Atlas-Scientific was the only pressure-capable probe
that was off-the-shelf.

Atlas-Scientific also offers a DO probe. A couple years ago I made a repo
with a sketch on how to get it running on an Arduino.
https://github.com/IanTBlack/OTP
Although I've recently begun to implement the Raspberry Pi in my work, so I
would recommend going that route if you are Python savvy. Whether you go
Arduino or RPi depends on your end use. Each has their own advantages.

If you do decide to build one, let me know. I have some parts that are
collecting dust and could be useful.

Let me know if you have any more questions,
-------------
Ian Black
Faculty Research Assistant | Ocean Observing Center
College of Earth, Ocean, and Atmospheric Sciences | Oregon State University
Cell: (541) 817-3687
