### ISSUE TITLE
Adafruit Feather MO Bluefruit LE [ID:2995]

### ISSUE THREAD

**Issue by MattChace** [OceanographyforEveryone/OpenCTD#26]
Not particularly an issue with this current design, but my team is trying to introduce the Bluetooth compatible Adalogger to the design to reduce the amount of times the CTD needs to be opened to access data (We have developed a GUI to display this data as well) and we recognize that the Arduino code needs to be altered to support bluetooth communication over serial/SD Card. A lot of the Adafruit demo code utilizes an app to link to the adalogger but we are aiming for a pc connection. I am looking for assistance with the arduino code for this if anyone has attempted it already or has any insight. As of now we only have the code written on this github page. The link to the bluetooth adalogger is below.
https://www.adafruit.com/product/2995?gclid=EAIaIQobChMIxu7496u56gIVjI7ICh3Sqg5jEAAYASAAEgJat_D_BwE

**Comment by IanTBlack** [comment]
Hi Matt,

The most recent version of the CTDizzle (based off the OpenCTD) uses the
Adafruit M0 Bluefruit.  You could probably cobble something together from
that repo. Note that I have not improved upon this code in some time and it
needs to be cleaned up. https://github.com/IanTBlack/CTDizzle

I have it set up to use the Bluefruit Android App, but there may be example
sketches that will connect to a PC via Bluetooth. I wouldn't be surprised
if there is a Python library that supports BTLE or if Teraterm supports it.

Let me know if you run into any issues.
- Ian
