### ISSUE TITLE
Maximum depth of OpenCTD?

### ISSUE THREAD

**Issue by Geoboy2020** [OceanographyforEveryone/OpenCTD#27]
I would like to build an OpenCTD for use on Lake Chelan, max depth 453m (3rd deepest lake in the U.S.). What is the likely max operating depth of the current design? If it is on the order of 200m, are there obvious modifications that could extend its operating depth to 500m? Would a mineral oil fill work for that purpose? 

I have an EXO3 that we deploy for profiles in shallower parts of the lake, but it only goes to 250m max depth. 

The EXO3 will provide a commercial instrument comparison with OpenCTD profiles to 250m depth if we can manage to build one.

Phil Long
Lake Chelan Research Institute 
KeepChelanBlue.org

**Comment by IanTBlack** [comment]
Hi Phil,

I believe Andrew has tested it to ~120m on the newer version. I'll have to
do some research on the pressure sensor, but your max operating range is 14
bar, so you'd have to upgrade to a new pressure sensor. You'd probably also
want to find an alternative to the plug cap.

You could try using a Blue Robotics aluminum case, which is what I have
done in my open source CTD builds.

Alternatively, you could increase the schedule of the PVC and pack on the
epoxy.

I'm travelling across the country right now. I should be able to give you a
more detailed response once I get back home.

Cheers,
- Ian

**Comment by DrAndrewThaler** [comment]
Hello,

We've tested the housing to 150 meters, however, the depth sensor is currently only rated to 14Bar, which works out to about 140 meters (with slight variation depending on water density and altitude). There is a 30 bar module that will get you the 300 meters which I am working on integrating. Source code is still being tested, but I'd be happy to send you the BoM and code to test as long as you understand that it's super provisional and hasn't been field tested yet. 

~Andrew
