### ISSUE TITLE
Battery polarity - important note when ordering the Amazon LiPos

### ISSUE THREAD

**Issue by pwnel** [OceanographyforEveryone/OpenCTD#38]
When ordering LiPo batteries from Amazon (using the Amazon link in the construction manual instead of the Adafruit link), be advised that the Amazon LiPos come with the polarity of the JST connector REVERSED.  The [M0 manual ](https://cdn-learn.adafruit.com/downloads/pdf/adafruit-feather-m0-adalogger.pdf )calls this out specifically (red box from manual inserted below) and it's worth adding this warning in the next iteration of the construction manual.  (NOTE: AdaFruit is out of stock of the LiPo batteries at this time, so it's useful to have the Amazon alternative - provided one is aware of the polarity issue)

<img width="1096" alt="Screen Shot 2024-02-14 at 4 10 19 PM" src="https://github.com/OceanographyforEveryone/OpenCTD/assets/9678065/db8e6ea2-0198-485c-9440-db46c3068d3b">

**Comment by DrAndrewThaler** [comment]
Thank you! That is so frustrating.
